### PR TITLE
v1 Rewrite

### LINKED ISSUE #3: Errors found without any errors on changed files
I've experienced an issue where Balto is showing a check as failed with a lot of errors, even though it does not list any errors.  I have also manually verified locally that the files in question do not contain errors.

The issue can be seen on this PR: https://github.com/ministrycentered/check-ins/pull/3548

### PR DESCRIPTION
**Pull request by sheck**
In this PR I rewrote the action in TypeScript and swapped Github check runs for workflow command output powered annotations. This is a culmination of a lot of internal discussion, planning, and unexpected delays.

The core motivation is this: there have been longstanding **issues with Github check runs initiated from Github actions**, specifically that they get associated with the incorrect action run. Github now recommends using workflow output command annotations for situations like this.

There are also other issues we wanted to address:
- Check run permission headaches
- Simplifying dependency install
- Lack of tests
- Input and output variable naming using camelCase instead of kebab-case

### Breaking changes

- Similar to when we changed [balto-rubocop to use workflow command output](https://github.com/planningcenter/balto-rubocop/pull/32), there is no way to have `balto-eslint` display a `neutral` conclusion.
  - This has been [heavily](https://github.com/actions/runner/issues/662) [requested](https://github.com/orgs/community/discussions/82744#discussioncomment-10615699) for many years now, but we're still waiting on Github
  - Users can specify a `conclusion-level` of `success` (the default) or `failure` to control how this affects the status of Github checks in the UI.
- Inputs and outputs use kebab-case now, which matches what Github (eventually) seemed to coalesce on as the standard
- We no longer manage installing dependencies and instead rely on balto-utils for a cached, speedy install of all JS dependencies
  - There was a non-insignificant amount of complexity involved in maintaining this feature that was implemented before caching was even possible with Github actions
- The source label name for annotations is now derived from job name, not hardcoded by us (it is recommended to call this action in a job named `balto-eslint` for labeling to be correct)

### Non-breaking changes

- We have official support for ESLint v9 now!
- We're using devbox to ensure we have a consistent development environment
- Using act for some somewhat manual, somewhat automatic testing
- I moved the `CONTRIBUTING.md` file to a section in the `README.md`

### Notes for reviewing

There's a lot here! Sorry! Everything outside of `src/` and `action.yml` are just supporting files though.

---

This should resolve #3 and #5

### CODE REVIEW

**Comment by markpalfreeman** [comment]
I don't feel prepared to review this PR, but if there comes a point where you need someone to test it, let me know! I have a [Giving branch](https://github.com/planningcenter/giving/tree/mp/eslint-flat-config) configured with ESLint v9 right now.

**Comment by sheck** [comment]
@markpalfreeman I'm meeting with the other Balto maintainers tomorrow morning to discuss this.

If you _want_ you can change your GitHub workflow to something like this to test on this branch:

```yaml
jobs:
  balto-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: planningcenter/balto-utils/yarn@v2
      - uses: planningcenter/balto-eslint@ns/v1
```

File: src/index.ts [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+    changedFiles = await detectChangedFiles(compareSha)
+  }
+
+  core.debug(`Changed files: ${changedFiles}`)
+
+  let { stdout: eslintOut } = await getExecOutput(
+    "npx eslint --format=json",
+    changedFiles,
+    // Eslint will return exit code 1 if it finds linting problems, but that is
+    // expected and we don't want to stop execution because of it.
```
Comment (danielma) [inline src/index.ts:45]: Thank you for this comment

File: src/eslint_result.ts [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+  private relevantMessages: EslintMessage[] = []
+
+  constructor(resultObject: ResultObject, compareSha: string) {
+    this.resultObject = resultObject
+    this.compareSha = compareSha
+  }
+
+  async asyncInitialize() {
+    this.changeRanges = await generateChangeRanges(
+      this.resultObject.filePath,
```
Comment (danielma) [inline src/eslint_result.ts:39]: Is `filePath` relative or absolute? My headspace for the question comes from noting distinction in how we build the array of changed files. Sometimes those are relative to the `workingDir` vs relative to the git root. However, based on my checking locally, `git diff --name-only` always outputs the path from the git root

File: src/git_utils.ts [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+  )
+  const udfLines = stdout.split("\n").filter((l) => l.match(/^@@.+\+\d/))
+
+  return udfLines
+    .map((l) => l.match(/\+(?<rangeStart>\d+)(?:,(?<rangeLength>\d*))?/))
+    .filter((m) => m)
+    .map((match) => {
+      const rangeStart = parseInt(match!.groups!.rangeStart, 10)
+      const rangeLength = match!.groups!.rangeLength
+        ? parseInt(match!.groups!.rangeLength) - 1
```
Comment (danielma) [inline src/git_utils.ts:29]:
```suggestion
        ? parseInt(match!.groups!.rangeLength, 10) - 1
```

File: src/eslint_result.ts [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+    this.relevantMessages = this.messages.filter((m) =>
+      this.changeRanges?.some((changeRange) => changeRange.doesInclude(m.line)),
+    )
+  }
+
+  private calculateCounts() {
+    this.relevantMessages.forEach((msg) => {
+      switch (msg.severity) {
+        case 1:
+          this.relevantWarningCount += 1
```
Comment (danielma) [inline src/eslint_result.ts:78]: The imperative nature of this class has me wondering if we could find a more imperative mental model to generate the results we want. I wonder what it would look like if we waited to initialize the `EslintResult` until we'd generated the data we care about. Maybe we could have a `static async` function on `EslintResult` that transforms the `ResultObject` into a fully-formed `EslintResult`.

It might be something like

```ts
class EslintResult {
    static async function fromResult(result: ResultObject, compareSha: string) {
        const changeRanges = await generateChangeRanges(result.filePath, compareSha)
        const relevantMessages = result.messages.filter(m => changeRanges.some(cr => cr.doesInclude(m.line)))
        const { warningCount, errorCount } = calculateCounts(relevantMessages)

        return new EslintResult({ result, relevantMessages, warningCount, errorCount })
    }

    static function calculateCounts(messages: ResultObject['messages']) {
        return messages.reduce((acc, message) => {
            switch (message.severity) {
                case 1:
                    acc.warningCount += 1
                    break
                case 2:
                    acc.errorCount += 1
                    break
            }

            return acc
        }, { warningCount: 0, errorCount: 0 })
    }
}
```

We can still initialize all the objects async (with `Promise.all`), but we no longer need to call instance methods in a certain order for them to be valid.

File: src/eslint_result.ts [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+      let options: core.AnnotationProperties = {
+        title: msg.ruleId,
+        file: this.repoFilePath,
+        startLine: msg.line,
+        endLine: msg.endLine,
+        startColumn: msg.column,
+        endColumn: msg.endColumn,
+      }
+      switch (msg.severity) {
+        case 1:
```
Comment (danielma) [inline src/eslint_result.ts:57]: Purely for readability, maybe let's extract an enum for severity

```ts
enum Severity {
    Warning = 1,
    Error = 2
}
```

**Review by danielma — APPROVED** [review]
This looks great. Using the `core` package to make annotations in STDOUT is clearly the blessed path going forward, and at the end of the day it's a lot easier to reason about when it's _just_ STDOUT rather than API interactions.

Honestly, I really only have one big question, which is about the order-dependent API of `EslintResult`. I _think_ we can find an API that more directly acknowledges the async initialization process, and we'll be in good shape.

Also, a _huge_ thank you for writing tests for this project. That makes the whole thing so much more viable to maintain and keep working on into the future 🍻

**Review by molawson — APPROVED** [review]
We talked this over on a call, and I feel great about this, especially the overall simplification and the addition of tests!

File: src/eslint_result.ts (hunk 5 above)
Comment (sheck) [reply src/eslint_result.ts:57]: Great call 👍

File: src/eslint_result.ts (hunk 2 above)
Comment (sheck) [reply src/eslint_result.ts:39]: That is a good question. After looking myself, it seems `filePath` from eslint is an absolute path. Git appears to not mind that we are calling diff on an absolute path.

The file paths that _we_ give to eslint are from the working directory though, as we manipulate the path to scope it to the working directory here: https://github.com/planningcenter/balto-eslint/blob/2f523c73941b74566ba8951a46e991e99f98f055/src/git_utils.ts#L53-L55

File: src/eslint_result.ts (hunk 4 above)
Comment (sheck) [reply src/eslint_result.ts:78]: I like that idea, I'll take a look 👍

File: src/eslint_result.ts (hunk 2 above)
Comment (danielma) [reply src/eslint_result.ts:39]: Nice. Ok, that makes sense. Absolute file paths _from_ `eslint` seem good, and it makes sense that `git` would be happy with that. Thanks for answering!

**Comment by danielma** [comment]
That set of changes looks solid. I'm so excited to have this released!
